name: "Teslamate"
description: "Self-hosted Tesla data logger. Vereist de Teslamate Database addon."
version: "1.33.0"
slug: "teslamate"
init: false
homeassistant_api: false
auth_api: false
url: "https://github.com/adriankumpf/teslamate"

arch:
  - aarch64
  - amd64

startup: services
boot: auto
host_network: true

ports:
  4000/tcp: 4000

ports_description:
  4000/tcp: "Teslamate web interface"

map:
  - share:rw

options:
  encryption_key: "verander-dit-naar-een-geheim"
  db_password: "teslamate"
  mqtt_host: "localhost"
  mqtt_port: 1883
  grafana_url: "http://homeassistant.local:3001"

schema:
  encryption_key: str
  db_password: str
  mqtt_host: str
  mqtt_port: int
  grafana_url: str
