name: "Teslamate"
description: "Self-hosted Tesla data logger met PostgreSQL en Grafana ingebouwd."
version: "1.33.0"
slug: "teslamate"
init: false
homeassistant_api: false
auth_api: false
url: "https://github.com/adriankumpf/teslamate"

arch:
  - aarch64
  - amd64

startup: services
boot: auto
host_network: false

ports:
  4000/tcp: 4000
  3000/tcp: 3000

ports_description:
  4000/tcp: "Teslamate web interface"
  3000/tcp: "Grafana dashboards"

map:
  - share:rw

options:
  encryption_key: "verander-dit-naar-een-geheim"
  db_password: "teslamate"
  mqtt_host: "192.168.1.80"
  mqtt_port: 1883
  grafana_password: "admin"

schema:
  encryption_key: str
  db_password: str
  mqtt_host: str
  mqtt_port: int
  grafana_password: str
