[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:postgres]
command=/usr/local/bin/docker-entrypoint.sh postgres
autostart=true
autorestart=true
priority=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=POSTGRES_USER="%(ENV_POSTGRES_USER)s",POSTGRES_PASSWORD="%(ENV_POSTGRES_PASSWORD)s",POSTGRES_DB="%(ENV_POSTGRES_DB)s",PGDATA="%(ENV_PGDATA)s"

[program:teslamate]
command=/teslamate-start.sh
autostart=true
autorestart=true
priority=20
startsecs=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:grafana]
command=/grafana-start.sh
autostart=true
autorestart=true
priority=30
startsecs=15
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
