name: "Teslamate Database"
description: "PostgreSQL database voor Teslamate. Start deze addon als eerste."
version: "17.5"
slug: "teslamate_db"
init: false
homeassistant_api: false
auth_api: false
url: "https://github.com/onsmam/HA-Addons"

arch:
  - aarch64
  - amd64

startup: services
boot: auto
host_network: true

map:
  - share:rw

options:
  db_password: "teslamate"

schema:
  db_password: str
